[build]
  # Build command
  command = "npm run build"

  # Directory to publish (Vite default)
  publish = "dist"

# Specify Node.js version and configure secrets scanning
[build.environment]
  NODE_VERSION = "18"
  # Exclude service role key from secrets scanning - should only be used in development
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_SERVICE_ROLE_KEY"

# Redirect all requests to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"